version: "3.7"
services:
  app:
    build:
      args:
        user: root
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: crowdfunding-web
    container_name: crowdfunding
    environment:
      DB_HOST: db  # Make sure this matches the service name
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - app-network
    command: >
      sh -c "
      php artisan migrate --force &&
      php-fpm"
  db:
    image: mysql:5.7.22
    container_name: crowdfunding-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - app-network
  nginx:
    image: nginx:alpine
    container_name: crowdfunding-ngx
    restart: unless-stopped
    ports:
      - 8001:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx/crowdfunding-app.conf:/etc/nginx/conf.d/
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
