version: "3.7"
services:
  app:
    build:
      args:
        user: www
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: crowdfunding-web
    container_name: crowdfunding
    restart: unless-stopped
    ports:
      - "8001:80"
    working_dir: /var/www/
    environment:
        APP_URL: http://localhost
        DB_CONNECTION: mysql
        DB_HOST: db
        DB_PORT: 3306
        DB_DATABASE: cfd
        DB_USERNAME: root
        DB_PASSWORD: root
    volumes:
      - ../:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
    command: >
      sh -c "
      composer install &&
      php artisan migrate --force &&
      php artisan l5-swagger:generate &&
      apache2-foreground
      "

  db:
    image: mysql:5.7
    container_name: crowdfunding-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      DB_DATABASE: cfd
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8082:80"
    environment:
      - "PMA_HOST=db"
      - "UPLOAD_LIMIT:30M"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
